- name: Install containerd
  block:
    - name: Add docker repository
      ansible.builtin.shell: |	
              sudo dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
              sudo dnf makecache
              sudo dnf install -y containerd.io
              sudo mkdir -p /etc/containerd
              sudo containerd config default | sudo tee /etc/containerd/config.toml
              sudo systemctl restart containerd

    - name: Edit the config.toml
      ansible.builtin.replace:
        path: /etc/containerd/config.toml
        regexp: '^(\s*)SystemdCgroup\s*=.*'
        replace: '\1SystemdCgroup = true'

    - name: Start and enable containerd
      ansible.builtin.service:
        name: containerd
        enabled: yes
        state: restarted
